import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DishRail, MenuRail } from "@/components/menu-ui";
import { categories, featured, images, restaurant, reviews } from "@/lib/zayqa-data";
export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Zayqa Lounge — Where Flavour Meets Atmosphere"},{name:"description",content:"An evening of good food, beautiful surroundings and time well spent at Zayqa Lounge."},{property:"og:title",content:"Zayqa Lounge — Where Flavour Meets Atmosphere"},{property:"og:description",content:"Taste, connect and unwind in the warm evening atmosphere of Zayqa Lounge."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Restaurant",name:restaurant.name,address:restaurant.address,telephone:restaurant.phone,servesCuisine:["South Asian","Contemporary"],priceRange:"$$$",openingHours:"Mo-Su 12:00-23:00"})}]}),component:Home});
function Home(){return <div className="home-page">
<section className="hero"><img src={images.interior} alt="Warm evening dining room at Zayqa Lounge" width="1536" height="1024" fetchPriority="high"/><div className="hero-shade"/><div className="hero-center"><p className="hero-brand">ZAYQA <span>LOUNGE</span></p><h1><span>Where flavour</span><br/><em>meets atmosphere.</em></h1><p>An evening of good food, beautiful surroundings and time well spent.</p><div className="hero-actions"><Button asChild variant="cream"><Link to="/reserve">Reserve a table</Link></Button><Button asChild variant="creamOutline"><Link to="/menu">Explore menu</Link></Button></div></div><div className="hero-meta"><span>Open today · {restaurant.hours}</span><ArrowDown/></div></section>
<section className="intro section-pad"><p className="eyebrow">The Zayqa way</p><h2>A place to<br/>taste. connect. <em>unwind.</em></h2><div className="intro-grid"><p>Food that feels generous. A room made for lingering. Service that knows when to arrive and when to let the evening unfold.</p><div className="intro-image"><img src={images.table} alt="Candlelit table setting at Zayqa Lounge" loading="lazy" width="1200" height="1504"/></div></div></section>
<section className="kitchen section-pad"><div className="section-heading"><div><p className="eyebrow">From our kitchen</p><h2>Dishes with<br/><em>a point of view.</em></h2></div><Button asChild variant="text"><Link to="/menu">See the full menu <ArrowRight/></Link></Button></div><div className="featured-grid"><div className="feature-primary"><img src={images.biryani} alt="Signature clay-pot biryani" loading="lazy" width="1200" height="1504"/><div><span>Signature</span><h3>Clay-Pot Biryani</h3><p>Aged basmati, slow-cooked lamb, saffron and mint raita.</p><Link to="/menu/item/$slug" params={{slug:"signature-clay-pot-biryani"}}>Discover the dish →</Link></div></div><div className="feature-rail"><DishRail list={featured.slice(1)} label="Featured dishes"/></div></div></section>
<section className="menu-explore section-pad"><div className="section-heading"><div><p className="eyebrow">The menu</p><h2>Every course,<br/><em>considered.</em></h2></div><Button asChild variant="text"><Link to="/menu">Browse the full menu <ArrowRight/></Link></Button></div>{categories.map(c=><MenuRail key={c.slug} slug={c.slug}/>)}</section>
<section className="room"><div className="room-sticky"><img src={images.interior} alt="The lounge dining room" loading="lazy" width="1536" height="1024"/></div><div className="room-story"><p className="eyebrow">The room</p><h2>Arrive.</h2><p>Step in from the city and let the pace soften.</p><h2>Settle in.</h2><p>Deep seats, warm light and a table made ready.</p><h2>Dine.</h2><p>Plates for sharing, and a little more time than planned.</p><h2>Unwind.</h2><p>The evening is yours.</p></div></section>
<section className="experience-callout section-pad"><p className="eyebrow">The experience</p><h2>Come for the food.<br/><em>Stay for the atmosphere.</em></h2><div className="experience-triptych"><Link to="/experience"><img src={images.table} alt="The table" loading="lazy" width="1200" height="1504"/><span>The table</span></Link><Link to="/experience"><img src={images.kitchen} alt="The kitchen" loading="lazy" width="1504" height="1008"/><span>The kitchen</span></Link><Link to="/gallery"><img src={images.interior} alt="The evening" loading="lazy" width="1536" height="1024"/><span>The evening</span></Link></div></section>
<section className="home-gallery section-pad"><div><p className="eyebrow">A glimpse of Zayqa</p><h2>In the room,<br/><em>in the moment.</em></h2><Button asChild variant="text"><Link to="/gallery">View gallery <ArrowRight/></Link></Button></div><img src={images.lamb} alt="Lamb chops served at Zayqa" loading="lazy"/><img src={images.dessert} alt="Dessert at Zayqa" loading="lazy"/></section><section className="quote-band"><p className="eyebrow">What our guests say</p><div className="review-marquee" aria-label="Guest reviews"><div className="review-track">{[...reviews,...reviews].map((r,i)=><figure className="review-card" key={i} aria-hidden={i>=reviews.length}><blockquote>“{r.quote}”</blockquote><figcaption>— {r.name} · {r.detail}</figcaption></figure>)}</div></div></section>
<section className="private-home"><img src={images.kitchen} alt="Private dining service" loading="lazy" width="1504" height="1008"/><div><p className="eyebrow">Private dining</p><h2>For the occasions<br/><em>that matter.</em></h2><p>Gather around one table for celebrations, team dinners and evenings worth making your own.</p><Button asChild variant="cream"><Link to="/private-dining">Make an enquiry</Link></Button></div></section>
<section className="visit section-pad"><div><p className="eyebrow">Find Zayqa</p><h2>Your evening<br/><em>starts here.</em></h2></div><div className="visit-details"><p><strong>Today</strong><br/>Open · {restaurant.hours}</p><p>{restaurant.address}<br/>{restaurant.phone}</p><Button asChild><Link to="/location">Get directions</Link></Button></div></section>
<section className="reserve-home"><p className="eyebrow">Reservations</p><h2>A table,<br/><em>waiting for you.</em></h2><Button asChild variant="cream"><Link to="/reserve">Reserve a table</Link></Button></section>
</div>}
