import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Quantity, useAddedToast } from "@/components/menu-ui";
import { useCart } from "@/components/cart-context";
import { money } from "@/lib/zayqa-data";
import { getPublicMenu } from "@/lib/menu.functions";
export const Route=createFileRoute("/menu/item/$slug")({loader:async({params})=>{const menu=await getPublicMenu();const d=menu.dishes.find(x=>x.slug===params.slug);if(!d)throw notFound();return d},head:({loaderData})=>({meta:[{title:`${loaderData?.name??"Dish"} — Zayqa Lounge`},{name:"description",content:loaderData?.longDescription??"A dish from Zayqa Lounge."},{property:"og:title",content:`${loaderData?.name??"Dish"} — Zayqa Lounge`},{property:"og:description",content:loaderData?.longDescription??"A dish from Zayqa Lounge."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DishPage});
function DishPage(){const dish=Route.useLoaderData();const [quantity,setQuantity]=useState(1);const [selected,setSelected]=useState<string[]>([]);const {add}=useCart();const added=useAddedToast();const addons=dish.addOns.filter(a=>selected.includes(a.name));return <div className="dish-detail"><div className="dish-detail-image"><img src={dish.image} alt={dish.name} width="1200" height="1504"/></div><div className="dish-detail-copy"><Link to="/menu" className="back-link">← Back to menu</Link><p className="eyebrow">{dish.category}</p><h1>{dish.name}</h1><p className="dish-lede">{dish.longDescription}</p><p className="dish-price">{money(dish.price)}</p><dl><div><dt>Ingredients</dt><dd>{dish.ingredients.join(" · ")}</dd></div><div><dt>Dietary</dt><dd>{dish.dietary.join(" · ")||"Please ask our team"}</dd></div><div><dt>Allergens</dt><dd>{dish.allergens.join(" · ")||"None listed"}</dd></div></dl>{dish.addOns.length>0&&<fieldset className="addons"><legend>Make it yours</legend>{dish.addOns.map(a=><label key={a.name}><input type="checkbox" checked={selected.includes(a.name)} onChange={()=>setSelected(v=>v.includes(a.name)?v.filter(x=>x!==a.name):[...v,a.name])}/><span>{a.name}</span><span>+{money(a.price)}</span></label>)}</fieldset>}<div className="add-row"><Quantity value={quantity} onChange={setQuantity}/><Button onClick={()=>{add(dish,quantity,addons);added(dish.name,quantity)}}>Add to order · {money((dish.price+addons.reduce((s,a)=>s+a.price,0))*quantity)}</Button></div></div></div>}
