import { createFileRoute, Link } from "@tanstack/react-router";import { useEffect, useState } from "react";import { Check } from "lucide-react";import { Button } from "@/components/ui/button";import { formatDate } from "@/lib/zayqa-data";import { useRestaurant } from "@/hooks/use-restaurant";
type Booking={date:string;slot:string;guests:string;code?:string};
function downloadIcs(b:Booking,restaurant:{name:string;address:string}){const m=b.slot.match(/(\d+):(\d+)\s*(AM|PM)/i);if(!m)return;let h=Number(m[1])%12;if(m[3]?.toUpperCase()==="PM")h+=12;const day=b.date.replace(/-/g,"");const t=(hh:number)=>`${day}T${String(hh).padStart(2,"0")}${m[2]}00`;
 const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Zayqa Lounge//Reservations//EN","BEGIN:VEVENT",`UID:${b.code??day}@zayqalounge.com`,`DTSTART:${t(h)}`,`DTEND:${t(Math.min(h+2,23))}`,`SUMMARY:Dinner at ${restaurant.name}`,`LOCATION:${restaurant.address.replace(/,/g,"\\,")}`,`DESCRIPTION:Table for ${b.guests}${b.code?` · Confirmation ${b.code}`:""}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");
 const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([ics],{type:"text/calendar"}));a.download="zayqa-reservation.ics";a.click();URL.revokeObjectURL(a.href)}
export const Route=createFileRoute("/reservation-confirmation")({head:()=>({meta:[{title:"Your Table Awaits — Zayqa Lounge"},{name:"robots",content:"noindex"}]}),component:Done});function Done(){const [d,setD]=useState<Booking|null|undefined>(undefined);const restaurant=useRestaurant();
 // sessionStorage only exists in the browser; reading it during render makes the server and client HTML disagree.
 useEffect(()=>{let saved:Booking|null=null;try{saved=JSON.parse(sessionStorage.getItem("zayqa-reservation")||"null")}catch{/* ignore corrupt storage */}setD(saved?.date&&saved?.slot?saved:null)},[]);
 if(d===undefined)return <div className="confirmation" aria-busy="true"/>;
 if(!d)return <div className="confirmation"><p className="eyebrow">Reservations</p><h1>No booking<br/><em>to show yet.</em></h1><p>Once you reserve a table, your confirmation will appear here.</p><div className="button-pair"><Button asChild><Link to="/reserve">Reserve a table</Link></Button><Button asChild variant="outline"><Link to="/">Return home</Link></Button></div></div>;
 return <div className="confirmation"><span className="confirmation-mark"><Check/></span><p className="eyebrow">Reservation confirmed{d.code?` · ${d.code}`:""}</p><h1>Your table<br/><em>awaits.</em></h1><div className="reservation-card"><strong>{formatDate(d.date)} · {d.slot}</strong><span>{d.guests} {d.guests==="1"?"Guest":"Guests"}</span><span>Zayqa Lounge</span><span>{restaurant.address}</span></div><div className="button-pair"><Button onClick={()=>downloadIcs(d,restaurant)}>Add to calendar</Button><Button asChild variant="outline"><Link to="/location">Get directions</Link></Button></div></div>}
