import { createFileRoute, useNavigate } from "@tanstack/react-router";import { useEffect, useState } from "react";import { Button } from "@/components/ui/button";import { DateInput } from "@/components/ui/date-input";import { Input } from "@/components/ui/input";import { Textarea } from "@/components/ui/textarea";import { supabase } from "@/integrations/supabase/client";import { formatDate, localDateKey } from "@/lib/zayqa-data";
const SLOTS=["6:00 PM","6:30 PM","7:30 PM","8:00 PM","8:30 PM","9:15 PM"];
const slotMinutes=(t:string)=>{const m=t.match(/(\d+):(\d+)\s*(AM|PM)/i);if(!m)return 0;return (Number(m[1])%12+(m[3]?.toUpperCase()==="PM"?12:0))*60+Number(m[2])};
export const Route=createFileRoute("/reserve")({head:()=>({meta:[{title:"Reserve a Table — Zayqa Lounge"},{name:"description",content:"Reserve your table at Zayqa Lounge."},{property:"og:title",content:"Reserve a Table — Zayqa Lounge"},{property:"og:description",content:"Choose a date, time and table at Zayqa Lounge."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Reserve});function Reserve(){const nav=useNavigate();const [step,setStep]=useState(1);const [picked,setSlot]=useState("");const [details,setDetails]=useState({date:"",guests:"2"});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 // "Today" must come from the visitor's clock, which the server doesn't know, so it's filled in after mount.
 const [today,setToday]=useState("");useEffect(()=>setToday(localDateKey()),[]);
 const now=new Date();const isPast=(t:string)=>details.date===today&&slotMinutes(t)<=now.getHours()*60+now.getMinutes();
 const dateOk=!!details.date&&(!today||details.date>=today);
 const slot=picked&&!isPast(picked)?picked:"";
 async function done(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError("");const f=new FormData(e.currentTarget);const code=`ZQR${Math.floor(1000+Math.random()*9000)}`;try{const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("reservations").insert({confirmation_code:code,user_id:user?.id??null,guest_name:String(f.get("name")),email:String(f.get("email")),phone:String(f.get("phone")),reservation_date:details.date,reservation_time:slot,guests:Number(details.guests),notes:String(f.get("notes"))||null});if(error)throw error;sessionStorage.setItem("zayqa-reservation",JSON.stringify({...details,slot,code}));nav({to:"/reservation-confirmation"})}catch{setError("We couldn’t confirm that table just now. Please call us instead.")}finally{setBusy(false)}}
 return <div className="reserve-page"><header className="page-hero reserve-hero"><p className="eyebrow">Reservations</p><h1>Reserve<br/><em>your table.</em></h1><p>Join us for lunch, dinner, or the part of the evening that becomes both.</p></header><section className="reservation-panel"><div className="step-count">0{step} / 02</div>{step===1?<div><h2>Find a table</h2><div className="field-grid"><label>Date<DateInput required value={details.date} min={today||undefined} onChange={e=>setDetails({...details,date:e.target.value})} aria-invalid={!!details.date&&!dateOk} aria-label="Choose reservation date"/></label><label>Guests<select aria-label="Number of guests" value={details.guests} onChange={e=>setDetails({...details,guests:e.target.value})}>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label></div>{details.date&&!dateOk&&<p className="form-error" role="alert">Please choose today or a later date.</p>}<p className="slot-label">Available times</p><div className="time-slots">{SLOTS.map(t=><button type="button" key={t} disabled={isPast(t)} className={slot===t?"active":""} onClick={()=>setSlot(t)}>{t}</button>)}</div><Button disabled={!slot||!dateOk} onClick={()=>setStep(2)}>Continue</Button></div>:<form onSubmit={done}><button type="button" className="back-link" onClick={()=>setStep(1)}>← Change time</button><h2>Your details</h2><div className="field-grid"><label>Name<Input name="name" required autoComplete="name"/></label><label>Email<Input name="email" required type="email" autoComplete="email"/></label><label>Phone<Input name="phone" required type="tel" autoComplete="tel"/></label></div><label>Anything we should know?<Textarea name="notes" placeholder="Celebration, accessibility or dietary notes"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<p className="booking-recap">{formatDate(details.date)} · {slot} · {details.guests} {details.guests==="1"?"guest":"guests"}</p><Button type="submit" disabled={busy}>{busy?"Confirming…":"Confirm reservation"}</Button></form>}</section></div>}
