import { Link } from "@tanstack/react-router";
import { Minus, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/components/cart-context";
import { categories, dishes, money, type CategorySlug, type Dish } from "@/lib/zayqa-data";
export function CategoryNav({active}:{active?:CategorySlug}){return <nav className="category-nav" aria-label="Menu categories">{categories.map(c=><Link key={c.slug} to="/menu/$category" params={{category:c.slug}} className={active===c.slug?"active":""}>{c.name}</Link>)}</nav>}
export function DishCard({dish}:{dish:Dish}){const {add}=useCart();return <article className="dish-card"><Link to="/menu/item/$slug" params={{slug:dish.slug}} className="dish-image"><img src={dish.image} alt={dish.name} loading="lazy" width="1200" height="1504"/></Link><div className="dish-card-copy"><div><Link to="/menu/item/$slug" params={{slug:dish.slug}}><h3>{dish.name}</h3></Link><p>{dish.description}</p></div><div className="dish-card-bottom"><span>{money(dish.price)}</span><Button variant="text" onClick={()=>add(dish)}>Add</Button></div></div></article>}
export function MenuCategory({slug}:{slug:CategorySlug}){const cat=categories.find(c=>c.slug===slug);const list=dishes.filter(d=>d.category===slug);if(!cat)return null;return <section className="menu-category" id={slug}><div className="section-kicker">{String(categories.indexOf(cat)+1).padStart(2,"0")}</div><div className="menu-category-head"><div><h2>{cat.name}</h2><p>{cat.intro}</p></div><Link to="/menu/$category" params={{category:slug}}>View category →</Link></div><div className="dish-rail">{list.map(d=><DishCard key={d.slug} dish={d}/>)}</div></section>}
export function Quantity({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="quantity"><Button variant="ghost" size="icon" aria-label="Decrease quantity" onClick={()=>onChange(Math.max(1,value-1))}><Minus/></Button><span>{value}</span><Button variant="ghost" size="icon" aria-label="Increase quantity" onClick={()=>onChange(value+1)}><Plus/></Button></div>}
