import { Link } from "@tanstack/react-router";
import { ChevronLeft, ChevronRight, Minus, Plus } from "lucide-react";
import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { useCart } from "@/components/cart-context";
import { categories, dishes, money, type CategorySlug, type Dish } from "@/lib/zayqa-data";
export function CategoryNav({active}:{active?:CategorySlug}){return <nav className="category-nav" aria-label="Menu categories">{categories.map(c=><Link key={c.slug} to="/menu/$category" params={{category:c.slug}} className={active===c.slug?"active":""}>{c.name}</Link>)}</nav>}
export function DishCard({dish}:{dish:Dish}){const {add}=useCart();return <article className="dish-card"><Link to="/menu/item/$slug" params={{slug:dish.slug}} className="dish-image"><img src={dish.image} alt={dish.name} loading="lazy" width="1200" height="1504"/></Link><div className="dish-card-copy"><div><Link to="/menu/item/$slug" params={{slug:dish.slug}}><h3>{dish.name}</h3></Link><p>{dish.description}</p></div><div className="dish-card-bottom"><span>{money(dish.price)}</span><Button variant="text" onClick={()=>add(dish)}>Add</Button></div></div></article>}
export function MenuCategory({slug}:{slug:CategorySlug}){const cat=categories.find(c=>c.slug===slug);const list=dishes.filter(d=>d.category===slug);if(!cat)return null;return <section className="menu-category" id={slug}><div className="section-kicker">{String(categories.indexOf(cat)+1).padStart(2,"0")}</div><div className="menu-category-head"><div><h2>{cat.name}</h2><p>{cat.intro}</p></div><Link to="/menu/$category" params={{category:slug}}>View category →</Link></div><div className="dish-rail">{list.map(d=><DishCard key={d.slug} dish={d}/>)}</div></section>}
export function DishRail({list,label}:{list:Dish[];label:string}){const rail=useRef<HTMLDivElement>(null);const scrollBy=(dir:number)=>{const el=rail.current;if(!el)return;el.scrollBy({left:dir*el.clientWidth*.8,behavior:"smooth"})};return <div className="dish-carousel"><div className="dish-carousel-track" ref={rail} role="region" aria-label={label} tabIndex={0}>{list.map(d=><DishCard key={d.slug} dish={d}/>)}</div><div className="dish-carousel-nav"><Button variant="outline" size="icon" aria-label={`Previous ${label}`} onClick={()=>scrollBy(-1)}><ChevronLeft/></Button><Button variant="outline" size="icon" aria-label={`Next ${label}`} onClick={()=>scrollBy(1)}><ChevronRight/></Button></div></div>}
export function MenuRail({slug}:{slug:CategorySlug}){const cat=categories.find(c=>c.slug===slug);const list=dishes.filter(d=>d.category===slug);if(!cat)return null;return <section className="menu-rail" aria-label={cat.name}><div className="menu-rail-head"><div><span className="section-kicker">{cat.name}</span><h3>{cat.intro}</h3></div><Link to="/menu/$category" params={{category:slug}}>View {cat.name} →</Link></div><DishRail list={list} label={cat.name}/></section>}
export function Quantity({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="quantity"><Button variant="ghost" size="icon" aria-label="Decrease quantity" onClick={()=>onChange(Math.max(1,value-1))}><Minus/></Button><span>{value}</span><Button variant="ghost" size="icon" aria-label="Increase quantity" onClick={()=>onChange(value+1)}><Plus/></Button></div>}
