import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, ShoppingBag, X } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { CartProvider, useCart } from "@/components/cart-context";
import { restaurant } from "@/lib/zayqa-data";
const nav=[{to:"/menu",label:"Menu"},{to:"/experience",label:"Experience"},{to:"/about",label:"About"},{to:"/gallery",label:"Gallery"},{to:"/private-dining",label:"Private Dining"},{to:"/location",label:"Location"}] as const;
function Header(){const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const path=useRouterState({select:s=>s.location.pathname}); const {count}=useCart(); const home=path==="/";
 useEffect(()=>{const on=()=>setScrolled(scrollY>40); on();addEventListener("scroll",on,{passive:true});return()=>removeEventListener("scroll",on)},[]);
 useEffect(()=>setOpen(false),[path]); const dark=home&&!scrolled;
 return <><header className={`site-header ${dark?"site-header-over":"site-header-solid"}`}><Link to="/" className="wordmark" aria-label="Zayqa Lounge home">ZAYQA</Link><nav className="desktop-nav" aria-label="Main navigation">{nav.slice(0,5).map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</nav><div className="header-actions"><Link className="location-link" to="/location">Location</Link><Button asChild variant={dark?"lightOutline":"outline"} size="sm"><Link to="/reserve">Reserve</Link></Button><Link to="/cart" className="icon-link" aria-label={`Cart with ${count} items`}><ShoppingBag/><span>{count}</span></Link><Button className="menu-trigger" variant="ghost" size="icon" aria-label="Open menu" onClick={()=>setOpen(true)}><Menu/></Button></div></header>
 <div className={`mobile-menu ${open?"is-open":""}`} aria-hidden={!open}><div className="mobile-menu-top"><span className="wordmark">ZAYQA</span><Button variant="ghost" size="icon" aria-label="Close menu" onClick={()=>setOpen(false)}><X/></Button></div><nav>{nav.map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</nav><div className="mobile-menu-actions"><Button asChild variant="cream"><Link to="/reserve">Reserve a table</Link></Button><Button asChild variant="creamOutline"><Link to="/menu">Order online</Link></Button></div></div></>}
function Footer(){return <footer className="site-footer"><div><Link to="/" className="footer-brand">ZAYQA <small>LOUNGE</small></Link><p>{restaurant.tagline}</p></div><div className="footer-links">{nav.map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}<Link to="/contact">Contact</Link><Link to="/account">My account</Link></div><div><p>Open daily<br/>{restaurant.hours}</p><p>{restaurant.address}<br/>{restaurant.phone}</p></div><div className="footer-bottom"><span>© 2026 Zayqa Lounge</span><span>Instagram · Privacy · Terms</span></div></footer>}
function ShellInner({children}:{children:ReactNode}){const path=useRouterState({select:s=>s.location.pathname});if(path.startsWith("/admin"))return <main>{children}</main>;return <><Header/><main>{children}</main>{path!=="/reserve"&&<Link className="mobile-reserve-pill" to="/reserve">Reserve a table</Link>}<Footer/></>}
export function SiteShell({children}:{children:ReactNode}){return <CartProvider><ShellInner>{children}</ShellInner></CartProvider>}
